### ISSUE TITLE
Adjust Service#eligible_sick_days

### ISSUE THREAD

**Issue by skius** [stiftungswo/better-izivi#154]
Bei Marc abklären, wie genau es mit der Anzahl anrechenbarer Krankheitstagen ist.

Das ZIVI präsentiert folgende Tabelle:

Einsatzdauer (in Tagen) | Anrechenbare Abwesenheitstage infolge Krankheit/Unfall
-- | --
1-3 | 1
4-8 | 2
9-14 | 3
15-21 | 4
22-29 | 5
pro 30 Tage Einsatz | 6

Mir ist jedoch nicht klar, ob für einen Einsatz von z.B. 40 Tagen nun 6 (`floor(40 / 30) * 6`) oder 9 (`floor(40 / 30) * 6 + tabelle(40 % 30)`) Krankheitstage anrechenbar sind. Die [alte Lösung](https://github.com/stiftungswo/izivi/blob/262024b97b24a7a5a0dbdacd517d294fa970574e/api/app/ReportSheet.php#L252) scheint Letzteres zu verwenden.

**Comment by skius** [comment]
#182 implements this

**Comment by TheFehr** [comment]
I did take a quick look at this and as far as I can tell, is the latter suggestion the accurate one.
I tried both calculation with the data of my long service and only the latter one matched with what eZivi tells me is correct.

**Comment by skius** [comment]
Feel free to merge #182 in that case.
