### ISSUE TITLE
Benutzer aus IZIVI ins Dime übertragen

### ISSUE THREAD

**Issue by swoadmin** [stiftungswo/better-izivi#169]
Originally reported by: **swo-admin NA (Bitbucket: [swo-admin](https://bitbucket.org/swo-admin), GitHub: Unknown)**

----------------------------------------

Im Dime werden alle ZIVIS aktuell von Hand, vom Einsatzleiter erfasst, um damit die Zeiterfassung zu machen. Es wäre praktisch wenn ein Zivi sich im Izivi registriert, direkt ein Nutzer im Dime dafür angelegt wird.

----------------------------------------
- Bitbucket: https://bitbucket.org/stiftungswo/izivi/issue/45

**Comment by ildacheu** [comment]
#391
