### ISSUE TITLE
Krankheitstage etc. direkt aus Dime auslesen für Spesenrapporte

### ISSUE THREAD

**Issue by swoadmin** [stiftungswo/better-izivi#170]
Originally reported by: **Simon Rösch (Bitbucket: [simonroesch](https://bitbucket.org/simonroesch), GitHub: [simonroesch](https://github.com/simonroesch))**

----------------------------------------

----------------------------------------
- Bitbucket: https://bitbucket.org/stiftungswo/izivi/issue/42

**Comment by TheFehr** [comment]
Siehe #225
