### ISSUE TITLE
Do we need #ignore_first_last_day?

### ISSUE THREAD

**Issue by lukasbischof** [stiftungswo/better-izivi#185]
In the production db, there's only one expense sheet that treats first and last day differently. However, it's in the middle of the service, therefore it seems more like a mistake.

**Comment by TheFehr** [comment]
- [ ] Remove from frontend, if not needed

**Comment by lukasbischof** [comment]
Can be removed, relict from legacy izivi

**Comment by ildacheu** [comment]
This feature was added again on behalf of this Issue #285 but with the option to differentiate between the first and the last workday. If the first or the last workday of the service is a vacation day, the Zivi also gets expenses for the breakfast on the second day or for the dinner on the second last day.
