### ISSUE TITLE
Änderung des Regionalzentrum wird nicht überall übernommen

### ISSUE THREAD

**Issue by BuesiVenoM** [stiftungswo/better-izivi#274]
Reporter: Marc Pfeuti

---

Wenn im eigenen Profil das Regionalzentrum geändert wird und danach eine neue Einsatzvereinbarung erstellt wird, wird der Header des PDFs korrekt ausgefüllt. Beim Rest des PDFs stimmt es aber nicht.

**Comment by TheFehr** [comment]
Those informations are stored in the [api/app/assets/pdfs/french_service_agreement_form.pdf](https://github.com/stiftungswo/better-izivi/blob/develop/api/app/assets/pdfs/french_service_agreement_form.pdf) this would need to be removed and dynamically filed as well

**Comment by stillhart** [comment]
#329
