### ISSUE TITLE
Profil - Einsatzplanung berechnet anzahl Diensttage nicht automatisch

### ISSUE THREAD

**Issue by BuesiVenoM** [stiftungswo/better-izivi#279]
Reporter: Marc Pfeuti

---

Wenn das Start- und Enddatum eingegeben wird, soll die Anzahl Diensttage direkt berechnet werden.
Wenn das Startdatum und die Anzahl Diensttage eingegeben wird, wird das Enddatum bereits ausgerechnet, der Weg andersrum sollte auch noch funktionieren.

**Comment by TheFehr** [comment]
It already works, but only if valid start and end dates are entered. (Start on monday and end on friday)
