### ISSUE TITLE
Single expense_sheet should be "publicable" for zivis

### ISSUE THREAD

**Issue by BuesiVenoM** [stiftungswo/better-izivi#305]
Reporter: Manuel Brändli

---

Bei Auszahlungen sollte pro Spesenblatt die Zahlung bestätigt werden können, so dass die Zivis diese im iZivi sehen können.
(Unter Auszahlungen in Liste der Spesenblätter war in der alten Version rechts ein Haken um diese Freizugeben)

**Comment by TheFehr** [comment]
Ist diese funktion wirklich notwendig? Man kann bereits auf einer Auszahlung alle angehörigen Spesenblätter als bestätigt markieren.

**Comment by lukasbischof** [comment]
Die Idee war, dass man nur die ganze Zahlung bestätigen kann, da man ja auch bei der Postfinance die ganze Auszahlung eingibt und diese entweder erfolgreich ist oder fehlschlägt. 
dies wurde von Andi auch bestätigt

**Comment by lukasbischof** [comment]
@BuesiVenoM

**Comment by ildacheu** [comment]
Da anscheinend jemand die Funktion implentiert hat, die ganze Zahlung kann bestätigt werden und der Zivi kann anschliessend das Spesenblatt herunterladen hat, schliesse ich dieses Issue jetzt
