### ISSUE TITLE
Single login should be enough to successfully login

### ISSUE THREAD

**Issue by Gumbee** [stiftungswo/better-izivi#314]
Reporter: Andreas Wolf

---

Login fails sometimes and multiple logins are required for it to finally work.

**Comment by lukasbischof** [comment]
@Gumbee Das isch wil s Authorization Token bim Login mitgsendet isch, au wenns abgloffe isch. Wenn mer bim request s exp field vom JWT tested und bim ablaufe s token löscht, setti s Problem behebe.
