### ISSUE TITLE
Tests fail occasionally

### ISSUE THREAD

**Issue by Gumbee** [stiftungswo/better-izivi#324]
Reporter: Mugeeb

---

The backend tests fail occasionally.

Example (for Build 200, 201):
Failed with seed 29399

Succeeded with seed 53432

**Comment by stillhart** [comment]
seems to happen after once a spec failed. Then the situation gets worse slowly.

**Comment by ildacheu** [comment]
added login to docker-hub since pulls from docker-hub are now limited and semaphore could mostly not pull them. If an authenticated user pulls the images the pulls are  counted for the user and not for the IP address.
