### ISSUE TITLE
Neues offizielles Formular für Einsatzvereinbarung.

### ISSUE THREAD

**Issue by dacin21** [stiftungswo/better-izivi#418]
Reporter:

Marc P.

---

Im iZivi muss das Formular "Einsatzvereinbarung" durch die neueste Version ersetzt werden.
Siehe E-Mail erhalten am 03.12.2021 15:38.

**Comment by dorianzgraggen** [comment]
@dacin21 machsch du das oder ich?

**Comment by dacin21** [comment]
wänn du Zit häsch, wärs cool wänn du s chöntisch mache, du häsch ja susch scho amigs s iZivi zügs gmacht. Ich bin no rächt mit em update vom Dime beschäftigt.

**Comment by dorianzgraggen** [comment]
jo chani mache
