### ISSUE TITLE
Anzahl Tage sind korrekt aber werden nicht gespeichert

### ISSUE THREAD

**Issue by dorianzgraggen** [stiftungswo/better-izivi#448]
Reporter: MZ

---

Die auf Ferien-, Krankheits- und Arbeitstage aufgeteilten Tage haben die korrekte Gesamtzahl, können aber nicht gespeichert werden.

**Comment by dorianzgraggen** [comment]
Beispiele:
https://izivi.stiftungswo.ch/expense_sheets/4991
https://izivi.stiftungswo.ch/expense_sheets/4900

**Comment by dorianzgraggen** [comment]
https://sentry.io/organizations/swo/issues/3057267394/?project=1447184&query=is%3Aunresolved

**Comment by luca-urti** [comment]
Wurde mit diesem Commit behoben.
https://github.com/stiftungswo/better-izivi/commit/2c3e12a10726ba1eadfe5a0fd60a6cb8afb23032
