### ISSUE TITLE
Fehlerhafte Berechnung von "Arbeitsfreien Tagen"

### ISSUE THREAD

**Issue by floerb** [stiftungswo/better-izivi#463]
Reporter:
Marc Pfeuti
---

Bei einem letzten Einsatz im Zeitraum vom 04.07.2022 - 25.07.2022 kommt es bei der Berechnung der Spesenblätter zu zu vielen "Arbeitsfreien Tagen". Lässt sich lokal bedingt reproduzieren.

**Comment by lukasbischof** [comment]
hat sich temporär geklärt oder sowas. Marc bringts nochmals ein, wenn es wieder kommt
