### ISSUE TITLE
Validate IBANs and make user check phone number + IBAN when creating new service

### ISSUE THREAD

**Issue by skius** [stiftungswo/better-izivi#47]
Bei "Neue Einsatzplanung hinzufügen" zuunterst zwei Checkboxen für IBAN und Telefonnummer hinzufügen "Ist diese Nummer noch aktuell" (wie AGB). Dort auch IBAN validieren.

**Comment by TheFehr** [comment]
Partially implemented, checkbox is added. User validation is not implemented yet.
