### ISSUE TITLE
Feedback Formular Prod: Funktioniert möglicherweise nicht mehr

### ISSUE THREAD

**Issue by floerb** [stiftungswo/better-izivi#486]
Reporter: Marc Pfeuti

---

Nach jedem Einsatz wird den Zivis ein Feedback-Formular zugesendet. Dieses wurde jedoch schon länger nicht mehr ausgefüllt. Es gilt zu prüfen, ob das Mail noch richtig rausgeht und das Formular noch funktioniert.

**Comment by TheFehr** [comment]
Nach Migration zu Google wurden die neuen E-Mail details nicht hinterlegt.
Ausserdem mag Google nicht wenn der EHOL / HELO Wert 'localhost' ist.
Dieser wird nun im nginx.conf gesetzt.
